### PR TITLE
added address and relative date of spill

### PR DESCRIPTION
**Pull request by fkh**
@jhubley I put the address at the top of the tooltip, in bold. I also added the relative date. The relative display depends on moment.js, an external library.

### CODE REVIEW

**Comment by jhubley** [comment]
@fkh Great! Thanks for adding -- makes sense to have these here.

**Comment by jhubley** [comment]
@fkh Actually-- I removed the date (for now) because when I tested at jillhubley.com/project/spills, all dates read as "15 years ago". Part of that was that the date format needed to be changed to work with D3. Did that, but then it said, "16 hours ago" for all spills. So commented out for now. Thanks for your input!

**Comment by fkh** [comment]
huh, very strange. It works for me -- see http://fkh.github.io/spills/. I had to reformat the csv to be comma-separated, maybe that's relevant?

**Comment by fkh** [comment]
Here's the documentation for the moment.js date parser. http://momentjs.com/docs/#/parsing/string-format/

There may be a better option, it was the first one I found.

**Comment by jhubley** [comment]
@fkh Yep, there were some values in the CSV that weren't reflected properly. Latest commit has what I changed. All is working well now including moment.js :)

**Comment by fkh** [comment]
Cool! This is a fascinating map.

On Wed, Apr 8, 2015 at 1:28 AM, Jill notifications@github.com wrote:

> @fkh https://github.com/fkh Yep, there were some values in the CSV that
> weren't reflected properly. Latest commit has what I changed. All is
> working well now including moment.js :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jhubley/spills/pull/2#issuecomment-90806372.

## 

Frank Hebbert
OpenPlans | http://openplans.org | 720 432-2378 | @fkh

**Pull request merged**
